[project]
name = "recipe-model"
version = "0.1.0"
description = "Add a short description here"
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
generate = "python model.py"
fmt = "black model.py"
check = "ruff model.py --fix --ignore E501"

[dependencies]
pydantic = "2.0.2.*"
ruff = "0.0.276.*"
black = "23.7.0.*"
